### PR TITLE
Create docs directory and add ERD file.

### PR DESCRIPTION
**Pull request by Jhonatanssal**
### Added:
- docs directory
- ERD with all tables with their respective diagrams.

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @jssarrazolaa and @SigmaSam 
### You have done well so far :clap: However, you have a few issues to fix:-
- [x] In the users' table, like id, name, and image_link. You can remove the dates and passwords as devise already comes with this
- [x] For friendship, make something like this id, user_id, friend_id, status. Also, remove the dates
- [x] Removes the timestamps as they are not necessary here, but you will have them in the database
### Make the changes and submit for another code review. Good luck.
- Happy coding!

**Review by voscarmv — CHANGES_REQUESTED** [review]
# Nice work so far, team. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- The relationship from comments to posts should be: 1 post has many comments. Your diagram shows the opposite, namely: 1 comment has many posts (this is incorrect) Please fix this!

- Also, your diagram shows that 1 like has many posts, and it should be the reverse: 1 post has many likes. Please correct this as well.

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

**Comment by Jhonatanssal** [comment]
> # Nice work so far, team. +1
> ## However, there are some changes required eyes toolbox hammer wrench
> 
>     * The relationship from comments to posts should be: 1 post has many comments. Your diagram shows the opposite, namely: 1 comment has many posts (this is incorrect) Please fix this!
> 
>     * Also, your diagram shows that 1 like has many posts, and it should be the reverse: 1 post has many likes. Please correct this as well.
> 
> 
> ### Submit these changes and request a new code review! smile +1
> ### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) technologistleft_speech_bubbletechnologist
> # Happy Hacking! brain keyboard computer_mouse desktop_computer

Thank you very much for making it so clear! 👍🏼

**Comment by jssarrazolaa** [comment]
> Hello @jssarrazolaa and @SigmaSam
> ### You have done well so far clap However, you have a few issues to fix:-
> 
>     * [x]  In the users' table, like id, name, and image_link. You can remove the dates and passwords as devise already comes with this
> 
>     * [x]  For friendship, make something like this id, user_id, friend_id, status. Also, remove the dates
> 
>     * [x]  Removes the timestamps as they are not necessary here, but you will have them in the database
> 
> 
> ### Make the changes and submit for another code review. Good luck.
> 
>     * Happy coding!

**Review by trekab — APPROVED** [review]
### Approved! :tada: 
Well done working on the suggested changes, team! Happy coding :wink: 

__Treasure Kabareebe__
[GitHub](https://github.com/trekab) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Pull request merged**
